import type { PortfolioContent } from "@shared/types/portfolio";

export const portfolioContent: PortfolioContent = {
  rootPortfolioId: "portfolio-patrik-egger",
  entities: [
    {
      id: "portfolio-patrik-egger",
      kind: "portfolio",
      slug: "patrik-egger",
      title: "Patrik Egger",
      summary:
        "Junior full-stack developer from Switzerland building practical apps with clear structure, documentation, and product thinking.",
      tags: ["portfolio", "full-stack", "product-minded"],
      status: "active",
      links: [
        {
          id: "github-profile",
          label: "GitHub",
          url: "https://github.com/N3on00",
        },
      ],
      payload: {
        headline:
          "Builds product-style applications with real architecture and reusable content foundations.",
        location: "Switzerland",
        modes: ["interactive", "classic"],
      },
    },
    {
      id: "block-hero",
      kind: "portfolio-block",
      slug: "hero",
      title: "Builder Snapshot",
      summary: "Introduces the overall profile, focus, and cross-mode framing.",
      tags: ["intro", "profile"],
      status: "active",
      payload: {
        blockType: "hero",
        audienceGoal: "Give both modes the same opening context without duplicating copy.",
      },
    },
    {
      id: "block-selected-projects",
      kind: "portfolio-block",
      slug: "selected-projects",
      title: "Selected Projects",
      summary: "Groups the strongest proof projects and the signals they carry.",
      tags: ["projects", "proof"],
      status: "active",
      payload: {
        blockType: "project-cluster",
        audienceGoal: "Expose lead projects to both quick-scan and exploratory mode renderers.",
      },
    },
    {
      id: "block-skill-clusters",
      kind: "portfolio-block",
      slug: "skill-clusters",
      title: "Skill Clusters",
      summary: "Collects the capabilities that repeat across multiple projects.",
      tags: ["skills", "taxonomy"],
      status: "active",
      payload: {
        blockType: "skill-cluster",
        audienceGoal: "Let each mode surface skills through project evidence instead of isolated buzzwords.",
      },
    },
    {
      id: "block-experience-timeline",
      kind: "portfolio-block",
      slug: "experience-timeline",
      title: "Experience Timeline",
      summary: "Summarizes the progression from coursework to product-style builds.",
      tags: ["experience", "timeline"],
      status: "active",
      payload: {
        blockType: "experience-timeline",
        audienceGoal: "Support a classic timeline and an interactive narrative path from the same entities.",
      },
    },
    {
      id: "block-contact",
      kind: "portfolio-block",
      slug: "contact",
      title: "Contact Surface",
      summary: "Keeps outbound profile links in the shared registry.",
      tags: ["contact", "links"],
      status: "active",
      payload: {
        blockType: "contact",
        audienceGoal: "Make contact details a shared block instead of a mode-specific footer copy.",
      },
    },
    {
      id: "object-desk-pc",
      kind: "interactive-object",
      slug: "desk-pc",
      title: "Desk PC",
      summary: "Primary project exploration object for deeper project overlays.",
      tags: ["interactive", "projects", "overlay"],
      status: "active",
      payload: {
        objectType: "desk",
        modeAnchors: ["interactive-room", "interactive-project-overlay"],
      },
    },
    {
      id: "object-wall-map",
      kind: "interactive-object",
      slug: "wall-map",
      title: "Wall Map",
      summary: "Anchors architecture and systems-thinking story fragments.",
      tags: ["interactive", "architecture", "story"],
      status: "active",
      payload: {
        objectType: "map",
        modeAnchors: ["interactive-room", "interactive-story-trail"],
      },
    },
    {
      id: "object-notebook-shelf",
      kind: "interactive-object",
      slug: "notebook-shelf",
      title: "Notebook Shelf",
      summary: "Connects reflection, documentation, and learning signals.",
      tags: ["interactive", "notes", "reflection"],
      status: "active",
      payload: {
        objectType: "shelf",
        modeAnchors: ["interactive-room", "interactive-story-trail"],
      },
    },
    {
      id: "story-builder",
      kind: "story-fragment",
      slug: "builder-story",
      title: "Builder First",
      summary: "Turns ideas into working prototypes with enough structure to keep growing them.",
      tags: ["story", "product", "execution"],
      status: "active",
      payload: {
        tone: "practical",
        prompt: "Use this when the mode needs a short narrative about shipping real software, not just coding exercises.",
      },
    },
    {
      id: "story-architecture",
      kind: "story-fragment",
      slug: "architecture-story",
      title: "Architecture Aware",
      summary: "Prefers modular contracts, documented decisions, and testable boundaries.",
      tags: ["story", "architecture", "maintainability"],
      status: "active",
      payload: {
        tone: "architectural",
        prompt: "Attach this to objects or sections that should explain structure, separation of concerns, or long-term maintainability.",
      },
    },
    {
      id: "story-documentation",
      kind: "story-fragment",
      slug: "documentation-story",
      title: "Documentation As Delivery",
      summary: "Treats setup docs, architecture notes, and portfolio curation as part of shipping.",
      tags: ["story", "documentation", "reflection"],
      status: "active",
      payload: {
        tone: "reflective",
        prompt: "Use this when an object or block should foreground clarity, repo hygiene, or communication.",
      },
    },
    {
      id: "hint-open-pc",
      kind: "story-hint",
      slug: "open-pc",
      title: "Open the PC",
      summary: "Hints that the desk PC reveals the strongest projects and their proof signals.",
      tags: ["hint", "projects"],
      status: "active",
      payload: {
        prompt: "Open the PC to inspect the strongest full-stack and prototype work.",
        targetObjectId: "object-desk-pc",
      },
    },
    {
      id: "hint-check-map",
      kind: "story-hint",
      slug: "check-map",
      title: "Check the Map",
      summary: "Hints that the wall map explains architecture and system-level thinking.",
      tags: ["hint", "architecture"],
      status: "active",
      payload: {
        prompt: "Check the wall map for the architecture thread across projects.",
        targetObjectId: "object-wall-map",
      },
    },
    {
      id: "hint-read-notes",
      kind: "story-hint",
      slug: "read-notes",
      title: "Read the Notes",
      summary: "Hints that the shelf ties documentation, iteration, and structured learning together.",
      tags: ["hint", "documentation"],
      status: "active",
      payload: {
        prompt: "Read the notes to see how documentation and reflection support delivery.",
        targetObjectId: "object-notebook-shelf",
      },
    },
    {
      id: "project-spotonsight",
      kind: "project",
      slug: "spotonsight",
      title: "SpotOnSight",
      summary: "Location-based social platform across web and mobile clients.",
      tags: ["full-stack", "vue", "fastapi", "mongodb", "mobile"],
      status: "active",
      links: [
        {
          id: "repo-spotonsight",
          label: "GitHub Repository",
          url: "https://github.com/N3on00/SpotOnSight",
        },
      ],
      payload: {
        role: "Lead portfolio project",
        timeframe: "Recent major project",
        stack: ["Vue", "FastAPI", "MongoDB", "Capacitor", "Docker", "GitHub Actions"],
        signals: [
          "full-stack architecture",
          "API design",
          "mobile wrapping",
          "CI/CD and docs",
        ],
      },
    },
    {
      id: "project-pay-qr",
      kind: "project",
      slug: "pay-qr-with-apple-pay",
      title: "pay-qr-with-apple-pay",
      summary: "Prototype app for QR invoice parsing and Apple Pay / Stripe payment flow.",
      tags: ["prototype", "payments", "vue", "express", "stripe"],
      status: "active",
      links: [
        {
          id: "repo-pay-qr",
          label: "GitHub Repository",
          url: "https://github.com/N3on00/pay-qr-with-apple-pay",
        },
      ],
      payload: {
        role: "Prototype and workflow project",
        timeframe: "Recent supporting project",
        stack: ["Vue 3", "Express", "Stripe", "QR parsing"],
        signals: [
          "product-flow design",
          "demo mode thinking",
          "frontend to backend integration",
        ],
      },
    },
    {
      id: "project-better-weather",
      kind: "project",
      slug: "better-weather",
      title: "better_weather",
      summary: "Multi-part weather and data project designed around runtime architecture and testability.",
      tags: ["python", "typescript", "testing", "architecture"],
      status: "active",
      links: [
        {
          id: "repo-better-weather",
          label: "GitHub Repository",
          url: "https://github.com/N3on00/better_weather",
        },
      ],
      payload: {
        role: "Architecture and integration project",
        timeframe: "Supporting systems project",
        stack: ["Python", "TypeScript", "service orchestration", "integration testing"],
        signals: [
          "registry-based architecture",
          "testability-first design",
          "cross-layer system thinking",
        ],
      },
    },
    {
      id: "project-m335",
      kind: "project",
      slug: "m335",
      title: "M335",
      summary: "Structured coursework project that reinforces process, discipline, and reflection.",
      tags: ["coursework", "documentation", "process"],
      status: "active",
      payload: {
        role: "Supporting evidence project",
        timeframe: "Coursework context",
        stack: ["documentation", "structured delivery"],
        signals: ["process discipline", "reflection", "supporting context"],
      },
    },
    {
      id: "skill-full-stack",
      kind: "skill",
      slug: "full-stack-development",
      title: "Full-Stack Delivery",
      summary: "Builds complete user-facing systems instead of isolated code samples.",
      tags: ["full-stack", "delivery"],
      status: "active",
      payload: {
        category: "engineering",
        level: "core",
        evidence: ["web frontend", "backend APIs", "deployment setup", "end-to-end thinking"],
      },
    },
    {
      id: "skill-frontend-vue",
      kind: "skill",
      slug: "frontend-vue",
      title: "Frontend Architecture with Vue",
      summary: "Uses Vue and modern web tooling to shape practical user flows and modular frontends.",
      tags: ["frontend", "vue", "vite"],
      status: "active",
      payload: {
        category: "frontend",
        level: "core",
        evidence: ["routing", "component structure", "user-flow design"],
      },
    },
    {
      id: "skill-api-backend",
      kind: "skill",
      slug: "api-backend",
      title: "Backend APIs and Service Separation",
      summary: "Structures backend responsibilities clearly across FastAPI, Express, and supporting services.",
      tags: ["backend", "fastapi", "express"],
      status: "active",
      payload: {
        category: "backend",
        level: "core",
        evidence: ["API design", "service separation", "environment setup"],
      },
    },
    {
      id: "skill-architecture-docs",
      kind: "skill",
      slug: "architecture-docs",
      title: "Architecture and Documentation",
      summary: "Documents structure, setup, and intent so projects stay understandable and maintainable.",
      tags: ["architecture", "documentation", "maintainability"],
      status: "active",
      payload: {
        category: "systems",
        level: "core",
        evidence: ["architecture notes", "repo organization", "setup docs", "content structuring"],
      },
    },
    {
      id: "skill-testing-runtime",
      kind: "skill",
      slug: "testing-runtime",
      title: "Testing and Runtime Discipline",
      summary: "Values testable contracts, integration-aware design, and repeatable environments.",
      tags: ["testing", "runtime", "quality"],
      status: "active",
      payload: {
        category: "quality",
        level: "supporting",
        evidence: ["integration testing", "CI/CD", "runtime structuring"],
      },
    },
    {
      id: "experience-junior-builder",
      kind: "experience",
      slug: "junior-builder",
      title: "Junior Full-Stack Builder",
      summary: "Breadth across frontend, backend, documentation, and deployment-ready project setup.",
      tags: ["experience", "full-stack", "junior"],
      status: "active",
      payload: {
        organization: "Personal and portfolio projects",
        timeframe: "Current stage",
        focusAreas: ["shipping MVPs", "cross-layer implementation", "iteration and cleanup"],
      },
    },
    {
      id: "experience-structured-coursework",
      kind: "experience",
      slug: "structured-coursework",
      title: "Structured Coursework and Reflection",
      summary: "Uses coursework projects as supporting evidence for process, discipline, and documentation quality.",
      tags: ["experience", "coursework", "process"],
      status: "active",
      payload: {
        organization: "Learning and assessed delivery",
        timeframe: "Supporting background",
        focusAreas: ["reflection", "process discipline", "documented learning"],
      },
    },
  ],
  relations: [
    {
      id: "portfolio-contains-hero",
      type: "contains",
      sourceId: "portfolio-patrik-egger",
      targetId: "block-hero",
      strength: "primary",
    },
    {
      id: "portfolio-contains-projects",
      type: "contains",
      sourceId: "portfolio-patrik-egger",
      targetId: "block-selected-projects",
      strength: "primary",
    },
    {
      id: "portfolio-contains-skills",
      type: "contains",
      sourceId: "portfolio-patrik-egger",
      targetId: "block-skill-clusters",
      strength: "primary",
    },
    {
      id: "portfolio-contains-experience",
      type: "contains",
      sourceId: "portfolio-patrik-egger",
      targetId: "block-experience-timeline",
      strength: "primary",
    },
    {
      id: "portfolio-contains-contact",
      type: "contains",
      sourceId: "portfolio-patrik-egger",
      targetId: "block-contact",
      strength: "primary",
    },
    {
      id: "portfolio-anchors-pc",
      type: "anchors",
      sourceId: "portfolio-patrik-egger",
      targetId: "object-desk-pc",
      strength: "supporting",
    },
    {
      id: "portfolio-anchors-map",
      type: "anchors",
      sourceId: "portfolio-patrik-egger",
      targetId: "object-wall-map",
      strength: "supporting",
    },
    {
      id: "portfolio-anchors-shelf",
      type: "anchors",
      sourceId: "portfolio-patrik-egger",
      targetId: "object-notebook-shelf",
      strength: "supporting",
    },
    {
      id: "hero-highlights-builder-story",
      type: "highlights",
      sourceId: "block-hero",
      targetId: "story-builder",
      strength: "primary",
    },
    {
      id: "hero-highlights-junior-experience",
      type: "highlights",
      sourceId: "block-hero",
      targetId: "experience-junior-builder",
      strength: "supporting",
    },
    {
      id: "projects-highlight-spotonsight",
      type: "highlights",
      sourceId: "block-selected-projects",
      targetId: "project-spotonsight",
      strength: "primary",
    },
    {
      id: "projects-highlight-pay-qr",
      type: "highlights",
      sourceId: "block-selected-projects",
      targetId: "project-pay-qr",
      strength: "primary",
    },
    {
      id: "projects-highlight-better-weather",
      type: "highlights",
      sourceId: "block-selected-projects",
      targetId: "project-better-weather",
      strength: "primary",
    },
    {
      id: "projects-highlight-m335",
      type: "highlights",
      sourceId: "block-selected-projects",
      targetId: "project-m335",
      strength: "supporting",
    },
    {
      id: "skills-highlight-full-stack",
      type: "highlights",
      sourceId: "block-skill-clusters",
      targetId: "skill-full-stack",
      strength: "primary",
    },
    {
      id: "skills-highlight-frontend",
      type: "highlights",
      sourceId: "block-skill-clusters",
      targetId: "skill-frontend-vue",
      strength: "primary",
    },
    {
      id: "skills-highlight-backend",
      type: "highlights",
      sourceId: "block-skill-clusters",
      targetId: "skill-api-backend",
      strength: "primary",
    },
    {
      id: "skills-highlight-architecture-docs",
      type: "highlights",
      sourceId: "block-skill-clusters",
      targetId: "skill-architecture-docs",
      strength: "primary",
    },
    {
      id: "skills-highlight-testing",
      type: "highlights",
      sourceId: "block-skill-clusters",
      targetId: "skill-testing-runtime",
      strength: "supporting",
    },
    {
      id: "experience-highlights-junior-builder",
      type: "highlights",
      sourceId: "block-experience-timeline",
      targetId: "experience-junior-builder",
      strength: "primary",
    },
    {
      id: "experience-highlights-coursework",
      type: "highlights",
      sourceId: "block-experience-timeline",
      targetId: "experience-structured-coursework",
      strength: "supporting",
    },
    {
      id: "contact-highlights-profile",
      type: "highlights",
      sourceId: "block-contact",
      targetId: "portfolio-patrik-egger",
      strength: "primary",
      note: "The root portfolio carries reusable outbound links.",
    },
    {
      id: "pc-reveals-project-block",
      type: "reveals",
      sourceId: "object-desk-pc",
      targetId: "block-selected-projects",
      strength: "primary",
    },
    {
      id: "pc-reveals-open-hint",
      type: "reveals",
      sourceId: "object-desk-pc",
      targetId: "hint-open-pc",
      strength: "supporting",
    },
    {
      id: "map-reveals-architecture-story",
      type: "reveals",
      sourceId: "object-wall-map",
      targetId: "story-architecture",
      strength: "primary",
    },
    {
      id: "shelf-reveals-documentation-story",
      type: "reveals",
      sourceId: "object-notebook-shelf",
      targetId: "story-documentation",
      strength: "primary",
    },
    {
      id: "hint-pc-points-to-object",
      type: "points-to",
      sourceId: "hint-open-pc",
      targetId: "object-desk-pc",
      strength: "primary",
    },
    {
      id: "hint-map-points-to-object",
      type: "points-to",
      sourceId: "hint-check-map",
      targetId: "object-wall-map",
      strength: "primary",
    },
    {
      id: "hint-shelf-points-to-object",
      type: "points-to",
      sourceId: "hint-read-notes",
      targetId: "object-notebook-shelf",
      strength: "primary",
    },
    {
      id: "builder-story-references-spotonsight",
      type: "references",
      sourceId: "story-builder",
      targetId: "project-spotonsight",
      strength: "primary",
    },
    {
      id: "builder-story-references-pay-qr",
      type: "references",
      sourceId: "story-builder",
      targetId: "project-pay-qr",
      strength: "supporting",
    },
    {
      id: "architecture-story-references-better-weather",
      type: "references",
      sourceId: "story-architecture",
      targetId: "project-better-weather",
      strength: "primary",
    },
    {
      id: "documentation-story-references-m335",
      type: "references",
      sourceId: "story-documentation",
      targetId: "project-m335",
      strength: "supporting",
    },
    {
      id: "spotonsight-demonstrates-full-stack",
      type: "demonstrates",
      sourceId: "project-spotonsight",
      targetId: "skill-full-stack",
      strength: "primary",
    },
    {
      id: "spotonsight-demonstrates-frontend",
      type: "demonstrates",
      sourceId: "project-spotonsight",
      targetId: "skill-frontend-vue",
      strength: "primary",
    },
    {
      id: "spotonsight-demonstrates-backend",
      type: "demonstrates",
      sourceId: "project-spotonsight",
      targetId: "skill-api-backend",
      strength: "primary",
    },
    {
      id: "spotonsight-demonstrates-docs",
      type: "demonstrates",
      sourceId: "project-spotonsight",
      targetId: "skill-architecture-docs",
      strength: "supporting",
    },
    {
      id: "pay-qr-demonstrates-frontend",
      type: "demonstrates",
      sourceId: "project-pay-qr",
      targetId: "skill-frontend-vue",
      strength: "primary",
    },
    {
      id: "pay-qr-demonstrates-backend",
      type: "demonstrates",
      sourceId: "project-pay-qr",
      targetId: "skill-api-backend",
      strength: "primary",
    },
    {
      id: "better-weather-demonstrates-architecture",
      type: "demonstrates",
      sourceId: "project-better-weather",
      targetId: "skill-architecture-docs",
      strength: "primary",
    },
    {
      id: "better-weather-demonstrates-testing",
      type: "demonstrates",
      sourceId: "project-better-weather",
      targetId: "skill-testing-runtime",
      strength: "primary",
    },
    {
      id: "m335-supports-documentation",
      type: "supports",
      sourceId: "project-m335",
      targetId: "skill-architecture-docs",
      strength: "supporting",
    },
    {
      id: "junior-experience-supports-full-stack",
      type: "supports",
      sourceId: "experience-junior-builder",
      targetId: "skill-full-stack",
      strength: "primary",
    },
    {
      id: "coursework-supports-documentation",
      type: "supports",
      sourceId: "experience-structured-coursework",
      targetId: "skill-architecture-docs",
      strength: "supporting",
    },
  ],
  modeMappings: [
    {
      id: "classic-shared-foundation",
      mode: "classic",
      surfaces: [
        {
          id: "classic-overview",
          label: "Classic Overview",
          rootEntityIds: ["block-hero"],
          relationTraversal: ["highlights", "supports", "references"],
          notes: [
            "Renders the root introduction and the strongest narrative thread first.",
          ],
        },
        {
          id: "classic-projects",
          label: "Classic Projects",
          rootEntityIds: ["block-selected-projects"],
          relationTraversal: ["highlights", "demonstrates"],
          notes: [
            "Project cards should be derived from project entities plus their demonstrated skills.",
          ],
        },
        {
          id: "classic-skills",
          label: "Classic Skills",
          rootEntityIds: ["block-skill-clusters"],
          relationTraversal: ["highlights", "supports", "demonstrates"],
          notes: [
            "Skill summaries should stay evidence-backed by following incoming project and experience relations.",
          ],
        },
        {
          id: "classic-experience",
          label: "Classic Experience",
          rootEntityIds: ["block-experience-timeline"],
          relationTraversal: ["highlights", "supports"],
          notes: ["Timeline rows should come from shared experience entities only."],
        },
        {
          id: "classic-contact",
          label: "Classic Contact",
          rootEntityIds: ["block-contact"],
          relationTraversal: ["highlights"],
          notes: ["Contact links are stored on the root portfolio entity and referenced through the block."],
        },
      ],
    },
    {
      id: "interactive-shared-foundation",
      mode: "interactive",
      surfaces: [
        {
          id: "interactive-room",
          label: "Interactive Room",
          rootEntityIds: ["object-desk-pc", "object-wall-map", "object-notebook-shelf"],
          relationTraversal: ["reveals", "anchors", "points-to", "references"],
          notes: [
            "Interactive objects are only anchors; the actual project, story, and skill data still lives in the shared registry.",
          ],
        },
        {
          id: "interactive-project-overlay",
          label: "Interactive Project Overlay",
          rootEntityIds: ["block-selected-projects"],
          relationTraversal: ["highlights", "demonstrates"],
          notes: ["The PC overlay can reuse the same project block as classic mode."],
        },
        {
          id: "interactive-story-trail",
          label: "Interactive Story Trail",
          rootEntityIds: ["hint-open-pc", "hint-check-map", "hint-read-notes"],
          relationTraversal: ["points-to", "reveals", "references", "supports"],
          notes: [
            "Hints should guide users toward existing entities instead of carrying duplicate explanatory content.",
          ],
        },
      ],
    },
  ],
  notes: [
    {
      id: "shared-content-single-source",
      text: "Entities are the durable source of truth; mode mappings only decide where they render.",
    },
    {
      id: "shared-content-block-graph",
      text: "Portfolio blocks group reusable entities so classic sections and interactive overlays can share the same source data.",
    },
    {
      id: "shared-content-hints-anchor",
      text: "Story hints and interactive objects remain lightweight anchors that point back into the same project, skill, and experience graph.",
    },
  ],
};
